name: Format After Merge

on:
  push:
    branches:
      - main

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff

      - name: Get changed files
        id: changed-files
        run: |
          echo "::set-output name=files::$(git diff --name-only HEAD^ HEAD | grep '\.py$' | xargs)"

      - name: Run ruff
        run: |
          ruff check --fix ${{ steps.changed-files.outputs.files }}

      - name: Update .git-ignore-revs
        run: |
          echo $(git rev-parse HEAD) >> .git-ignore-revs

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Apply formatting to changed files"
          title: "Format changed files"
          body: |
            This PR applies formatting to the files changed in the previous merge.
            - Ran `ruff` on changed Python files
            - Updated `.git-ignore-revs`
          branch: "auto-format-${{ github.sha }}"
          base: "main"

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Apply formatting to changed files"
          title: "Format changed files"
          body: |
            This PR applies formatting to the files changed in the previous merge.
            - Ran `ruff` on changed Python files
            - Updated `.git-ignore-revs`
          branch: "auto-format-${{ github.sha }}"
          base: "main"

      - name: Create Issue about Formatting PR
        if: always()
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const prNumber = '${{ steps.cpr.outputs.pull-request-number }}';
            const prCreated = '${{ steps.cpr.outcome }}' === 'success';
            const issueBody = prCreated
              ? `A formatting PR #${prNumber} has been created to apply formatting to recently changed files.`
              : 'An attempt to create a formatting PR was made, but it failed. You may want to manually create a PR to format recently changed files.';
            
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'Formatting PR Notification',
              body: issueBody
            });

